"""empty message

Revision ID: 0a37bcffad0f
Revises: bc9edd01aeb9
Create Date: 2024-08-04 22:14:24.701951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0a37bcffad0f'
down_revision: Union[str, None] = 'bc9edd01aeb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'modified_at')
    op.drop_column('replies', 'modified_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replies', sa.Column('modified_at', mysql.DATETIME(), nullable=True))
    op.add_column('post', sa.Column('modified_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
