"""empty message

Revision ID: 1d4bcf40e454
Revises: b3c009cc07b1
Create Date: 2024-08-04 22:09:33.306711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1d4bcf40e454'
down_revision: Union[str, None] = 'b3c009cc07b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('replies', 'modified_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replies', sa.Column('modified_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
