"""empty message

Revision ID: 4bcdb0164cd6
Revises: e6c13c1d1d71
Create Date: 2024-08-04 22:11:57.349410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4bcdb0164cd6'
down_revision: Union[str, None] = 'e6c13c1d1d71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'modified_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'modified_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
