"""empty message

Revision ID: 664445cbf02d
Revises: ff35c171d4fb
Create Date: 2024-09-22 21:29:18.038021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '664445cbf02d'
down_revision: Union[str, None] = 'ff35c171d4fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replies', sa.Column('voter_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('replies', 'voter_count')
    # ### end Alembic commands ###
