"""empty message

Revision ID: 6de3d833139d
Revises: 3ae1f89d8fd7
Create Date: 2024-07-14 20:30:48.642408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6de3d833139d'
down_revision: Union[str, None] = '3ae1f89d8fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replies', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'replies', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'replies', type_='foreignkey')
    op.drop_column('replies', 'user_id')
    # ### end Alembic commands ###
