"""empty message

Revision ID: b3c009cc07b1
Revises: 8734f840abe9
Create Date: 2024-08-04 22:08:03.233499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b3c009cc07b1'
down_revision: Union[str, None] = '8734f840abe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('replies', 'modified_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('replies', 'modified_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
