"""empty message

Revision ID: dec99033cfe9
Revises: 2623ff35539c
Create Date: 2024-06-30 20:37:56.586139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dec99033cfe9'
down_revision: Union[str, None] = '2623ff35539c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=254),
               type_=sa.String(length=60),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.String(length=60),
               type_=mysql.VARCHAR(length=254),
               existing_nullable=False)
    # ### end Alembic commands ###
