"""empty message

Revision ID: e6c13c1d1d71
Revises: 1d4bcf40e454
Create Date: 2024-08-04 22:09:40.392119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c13c1d1d71'
down_revision: Union[str, None] = '1d4bcf40e454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replies', sa.Column('modified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('replies', 'modified_at')
    # ### end Alembic commands ###
